//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DialogueGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDialogueGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class DialogueGrammarBaseListener : IDialogueGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] DialogueGrammarParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] DialogueGrammarParser.ScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.titleBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTitleBlock([NotNull] DialogueGrammarParser.TitleBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.titleBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTitleBlock([NotNull] DialogueGrammarParser.TitleBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.titleMeta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTitleMeta([NotNull] DialogueGrammarParser.TitleMetaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.titleMeta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTitleMeta([NotNull] DialogueGrammarParser.TitleMetaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.metaEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetaEntry([NotNull] DialogueGrammarParser.MetaEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.metaEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetaEntry([NotNull] DialogueGrammarParser.MetaEntryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] DialogueGrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] DialogueGrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompoundStatement([NotNull] DialogueGrammarParser.CompoundStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompoundStatement([NotNull] DialogueGrammarParser.CompoundStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementList([NotNull] DialogueGrammarParser.StatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementList([NotNull] DialogueGrammarParser.StatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.declarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationStatement([NotNull] DialogueGrammarParser.DeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.declarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationStatement([NotNull] DialogueGrammarParser.DeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.exprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStatement([NotNull] DialogueGrammarParser.ExprStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.exprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStatement([NotNull] DialogueGrammarParser.ExprStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.dialogueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDialogueStatement([NotNull] DialogueGrammarParser.DialogueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.dialogueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDialogueStatement([NotNull] DialogueGrammarParser.DialogueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.selectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectStatement([NotNull] DialogueGrammarParser.SelectStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.selectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectStatement([NotNull] DialogueGrammarParser.SelectStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.selectList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectList([NotNull] DialogueGrammarParser.SelectListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.selectList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectList([NotNull] DialogueGrammarParser.SelectListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection([NotNull] DialogueGrammarParser.SelectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection([NotNull] DialogueGrammarParser.SelectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] DialogueGrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] DialogueGrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpStatement([NotNull] DialogueGrammarParser.JumpStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpStatement([NotNull] DialogueGrammarParser.JumpStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] DialogueGrammarParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] DialogueGrammarParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclaratorList([NotNull] DialogueGrammarParser.InitDeclaratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclaratorList([NotNull] DialogueGrammarParser.InitDeclaratorListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclarator([NotNull] DialogueGrammarParser.InitDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclarator([NotNull] DialogueGrammarParser.InitDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] DialogueGrammarParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] DialogueGrammarParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarator([NotNull] DialogueGrammarParser.DeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarator([NotNull] DialogueGrammarParser.DeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer([NotNull] DialogueGrammarParser.InitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer([NotNull] DialogueGrammarParser.InitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializerList([NotNull] DialogueGrammarParser.InitializerListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializerList([NotNull] DialogueGrammarParser.InitializerListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] DialogueGrammarParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] DialogueGrammarParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.constantExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantExpr([NotNull] DialogueGrammarParser.ConstantExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.constantExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantExpr([NotNull] DialogueGrammarParser.ConstantExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.assignExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignExpr([NotNull] DialogueGrammarParser.AssignExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.assignExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignExpr([NotNull] DialogueGrammarParser.AssignExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.assignOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignOperator([NotNull] DialogueGrammarParser.AssignOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.assignOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignOperator([NotNull] DialogueGrammarParser.AssignOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] DialogueGrammarParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] DialogueGrammarParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] DialogueGrammarParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] DialogueGrammarParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpr([NotNull] DialogueGrammarParser.EqualityExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpr([NotNull] DialogueGrammarParser.EqualityExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpr([NotNull] DialogueGrammarParser.RelationalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpr([NotNull] DialogueGrammarParser.RelationalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpr([NotNull] DialogueGrammarParser.AdditiveExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpr([NotNull] DialogueGrammarParser.AdditiveExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpr([NotNull] DialogueGrammarParser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpr([NotNull] DialogueGrammarParser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.powerExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowerExpr([NotNull] DialogueGrammarParser.PowerExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.powerExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowerExpr([NotNull] DialogueGrammarParser.PowerExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpr([NotNull] DialogueGrammarParser.UnaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpr([NotNull] DialogueGrammarParser.UnaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.postfixExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixExpr([NotNull] DialogueGrammarParser.PostfixExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.postfixExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixExpr([NotNull] DialogueGrammarParser.PostfixExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.argumentExprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentExprList([NotNull] DialogueGrammarParser.ArgumentExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.argumentExprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentExprList([NotNull] DialogueGrammarParser.ArgumentExprListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpr([NotNull] DialogueGrammarParser.PrimaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpr([NotNull] DialogueGrammarParser.PrimaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] DialogueGrammarParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] DialogueGrammarParser.ValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
