//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DialogueGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DialogueGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDialogueGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] DialogueGrammarParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.titleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTitleBlock([NotNull] DialogueGrammarParser.TitleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.titleMeta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTitleMeta([NotNull] DialogueGrammarParser.TitleMetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.metaEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetaEntry([NotNull] DialogueGrammarParser.MetaEntryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DialogueGrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundStatement([NotNull] DialogueGrammarParser.CompoundStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] DialogueGrammarParser.StatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] DialogueGrammarParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.exprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStatement([NotNull] DialogueGrammarParser.ExprStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.dialogueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDialogueStatement([NotNull] DialogueGrammarParser.DialogueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectStatement([NotNull] DialogueGrammarParser.SelectStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.selectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectList([NotNull] DialogueGrammarParser.SelectListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection([NotNull] DialogueGrammarParser.SelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] DialogueGrammarParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] DialogueGrammarParser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] DialogueGrammarParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclaratorList([NotNull] DialogueGrammarParser.InitDeclaratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclarator([NotNull] DialogueGrammarParser.InitDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] DialogueGrammarParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarator([NotNull] DialogueGrammarParser.DeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] DialogueGrammarParser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerList([NotNull] DialogueGrammarParser.InitializerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] DialogueGrammarParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.constantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpr([NotNull] DialogueGrammarParser.ConstantExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.assignExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignExpr([NotNull] DialogueGrammarParser.AssignExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.assignOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignOperator([NotNull] DialogueGrammarParser.AssignOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] DialogueGrammarParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] DialogueGrammarParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpr([NotNull] DialogueGrammarParser.EqualityExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] DialogueGrammarParser.RelationalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] DialogueGrammarParser.AdditiveExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] DialogueGrammarParser.MultiplicativeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.powerExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExpr([NotNull] DialogueGrammarParser.PowerExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] DialogueGrammarParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.postfixExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpr([NotNull] DialogueGrammarParser.PostfixExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.argumentExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentExprList([NotNull] DialogueGrammarParser.ArgumentExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] DialogueGrammarParser.PrimaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DialogueGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] DialogueGrammarParser.ValueContext context);
}
