//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DialogueGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DialogueGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDialogueGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] DialogueGrammarParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] DialogueGrammarParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.titleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTitleBlock([NotNull] DialogueGrammarParser.TitleBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.titleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTitleBlock([NotNull] DialogueGrammarParser.TitleBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.titleMeta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTitleMeta([NotNull] DialogueGrammarParser.TitleMetaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.titleMeta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTitleMeta([NotNull] DialogueGrammarParser.TitleMetaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.metaEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetaEntry([NotNull] DialogueGrammarParser.MetaEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.metaEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetaEntry([NotNull] DialogueGrammarParser.MetaEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] DialogueGrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] DialogueGrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStatement([NotNull] DialogueGrammarParser.CompoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStatement([NotNull] DialogueGrammarParser.CompoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementList([NotNull] DialogueGrammarParser.StatementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementList([NotNull] DialogueGrammarParser.StatementListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] DialogueGrammarParser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] DialogueGrammarParser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.exprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStatement([NotNull] DialogueGrammarParser.ExprStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.exprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStatement([NotNull] DialogueGrammarParser.ExprStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.dialogueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDialogueStatement([NotNull] DialogueGrammarParser.DialogueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.dialogueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDialogueStatement([NotNull] DialogueGrammarParser.DialogueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectStatement([NotNull] DialogueGrammarParser.SelectStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectStatement([NotNull] DialogueGrammarParser.SelectStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.selectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectList([NotNull] DialogueGrammarParser.SelectListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.selectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectList([NotNull] DialogueGrammarParser.SelectListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection([NotNull] DialogueGrammarParser.SelectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection([NotNull] DialogueGrammarParser.SelectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] DialogueGrammarParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] DialogueGrammarParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] DialogueGrammarParser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] DialogueGrammarParser.JumpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] DialogueGrammarParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] DialogueGrammarParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclaratorList([NotNull] DialogueGrammarParser.InitDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclaratorList([NotNull] DialogueGrammarParser.InitDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclarator([NotNull] DialogueGrammarParser.InitDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclarator([NotNull] DialogueGrammarParser.InitDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] DialogueGrammarParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] DialogueGrammarParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] DialogueGrammarParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] DialogueGrammarParser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] DialogueGrammarParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] DialogueGrammarParser.InitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerList([NotNull] DialogueGrammarParser.InitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerList([NotNull] DialogueGrammarParser.InitializerListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] DialogueGrammarParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] DialogueGrammarParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.constantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpr([NotNull] DialogueGrammarParser.ConstantExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.constantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpr([NotNull] DialogueGrammarParser.ConstantExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.assignExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignExpr([NotNull] DialogueGrammarParser.AssignExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.assignExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignExpr([NotNull] DialogueGrammarParser.AssignExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.assignOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignOperator([NotNull] DialogueGrammarParser.AssignOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.assignOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignOperator([NotNull] DialogueGrammarParser.AssignOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] DialogueGrammarParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] DialogueGrammarParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] DialogueGrammarParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] DialogueGrammarParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] DialogueGrammarParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] DialogueGrammarParser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] DialogueGrammarParser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] DialogueGrammarParser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] DialogueGrammarParser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] DialogueGrammarParser.AdditiveExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpr([NotNull] DialogueGrammarParser.MultiplicativeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpr([NotNull] DialogueGrammarParser.MultiplicativeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.powerExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowerExpr([NotNull] DialogueGrammarParser.PowerExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.powerExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowerExpr([NotNull] DialogueGrammarParser.PowerExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] DialogueGrammarParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] DialogueGrammarParser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.postfixExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpr([NotNull] DialogueGrammarParser.PostfixExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.postfixExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpr([NotNull] DialogueGrammarParser.PostfixExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.argumentExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentExprList([NotNull] DialogueGrammarParser.ArgumentExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.argumentExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentExprList([NotNull] DialogueGrammarParser.ArgumentExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpr([NotNull] DialogueGrammarParser.PrimaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpr([NotNull] DialogueGrammarParser.PrimaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DialogueGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] DialogueGrammarParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DialogueGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] DialogueGrammarParser.ValueContext context);
}
